# Michiel's notebook on Arrays with Numpy

Numpy = <b>Num</b>erical <b>py</b>thon

Numpy is a library tot create (mostly arrays). Examples are:
- shape(4,) 4 digits 1D array; uses 0 axis
- shape (2,3) - 2x3 array ; uses 1 axis
- shape (4,3,2) 4x3x2 array; uses 2 axis

Arrays use []

#### Arrays compared to lists
Arrays are better than lists:
- Lists are slow, arrays are faster
- Numpy is a fixed Type. 
    -  5 = binary 00000101 => Numpy=>  Int32 00000000 0000000 0000000 00000101
                              List => 10x zo veel memory

- No type checking when iterating through objects
- Numpy uses contiguous memory
- You can't multiply lists, but you can multiply arrays.

## Some introductions

In [64]:
# Import the numpy module for this Jupyter Notebook
import numpy as np

In [68]:
# create
import numpy as np # optional
#initialize an array
a = np.array([1,2,3]) # 1D array as a list
print(a)

[1 2 3]


In [63]:
#create an array with zero's
a = np.zeros(3)  # use an array of 1x3 with values of zero
print(a)
type(a)# show the type of array

[0. 0. 0.]


numpy.ndarray

In [49]:
#create an empty array
z = np.empty(3)
z

array([0., 0., 0.])

In [61]:
#create a random array with size 1x6
zl = np.random.randint(10,size=6)
zl

array([5, 6, 2, 4, 4, 8])

In [52]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)
b.ndim #get dimension
b.shape #shape of array
a.dtype # data type
a.itemsize #get size
a.size #total size 
b.nbytes # number of bytes (floats are bigger than integers)

[[9. 8. 7.]
 [6. 5. 4.]]


48

## Get and change specific cell(s) or row 

In [54]:
# Create two arrays:
a= np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)
a[1,5] #get specific element in row 1 and column 5)
a[0,:]# Get a specific row and column
a[:,2]
# startindex:endindex:stepsize
a[0, 1:6:2]
a[1,5] = 20 #change cell in 2nd row 6th column with value 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


## 3D Arrays

In [30]:
#3d exmaple

b = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


## Fill arrays with specific values

In [31]:
# Initialize arrays
# all 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [37]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [41]:
#random numbers
np.random.rand(4,2,3)

array([[[0.04373238, 0.67746989, 0.25351155],
        [0.69039661, 0.65479309, 0.96377195]],

       [[0.33302655, 0.43297432, 0.92398306],
        [0.63866472, 0.37841027, 0.81839676]],

       [[0.69926338, 0.54929744, 0.0978625 ],
        [0.38397338, 0.26621762, 0.18342968]],

       [[0.09336124, 0.26502812, 0.23935091],
        [0.20218478, 0.47362085, 0.42995994]]])

In [46]:
np.random.randint(4,7, size=(3,3)) #startvalue, shape

array([[4, 5, 5],
       [6, 6, 5],
       [6, 4, 4]])

In [47]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])