# Pytorch

Source: Sentdex
Video 1: https://www.youtube.com/watch?v=BzcBsTou0C0
Video 2: https://www.youtube.com/watch?v=i2yPxY2rOzs

In [1]:
%pip install torch

In [2]:
%pip install pytorch

  Running setup.py clean for pytorch

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\31653\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\31653\\AppData\\Local\\Temp\\pip-install-l72r6jdf\\pytorch\\setup.py'"'"'; __file__='"'"'C:\\Users\\31653\\AppData\\Local\\Temp\\pip-install-l72r6jdf\\pytorch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\31653\AppData\Local\Temp\pip-wheel-77rxt1o8'
       cwd: C:\Users\31653\AppData\Local\Temp\pip-install-l72r6jdf\pytorch\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>



Failed to build pytorch
    Running setup.py install for pytorch: started
    Running setup.py install for pytorch: finished with status 'error'


    File "C:\Users\31653\AppData\Local\Temp\pip-install-l72r6jdf\pytorch\setup.py", line 15, in <module>
      raise Exception(message)
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
  ----------------------------------------
  ERROR: Failed building wheel for pytorch
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\31653\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\31653\\AppData\\Local\\Temp\\pip-install-l72r6jdf\\pytorch\\setup.py'"'"'; __file__='"'"'C:\\Users\\31653\\AppData\\Local\\Temp\\pip-install-l72r6jdf\\pytorch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\31653\AppData\Local\Temp\pip-record-byqenu6h\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\31653\anaconda3\I

In [3]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y) # multiply the two arrays tensor is a multidimensional array

tensor([10.,  3.])


In [4]:
x = torch.zeros([2,5])

In [5]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [6]:
x.shape

torch.Size([2, 5])

In [8]:
y = torch.rand([2,5])
y

tensor([[0.8045, 0.1309, 0.6837, 0.9797, 0.1849],
        [0.0862, 0.2665, 0.3092, 0.5778, 0.7307]])

### Reshaping in Numpy => view in Pytorch

In [9]:
y.view([1,10])

tensor([[0.8045, 0.1309, 0.6837, 0.9797, 0.1849, 0.0862, 0.2665, 0.3092, 0.5778,
         0.7307]])

## 2. Torchvision

In [10]:
%pip install torchvision

Note: you may need to restart the kernel to use updated packages.


In [12]:
import torch 
import torchvision
from torchvision import transforms, datasets # load some built in datasets

In [15]:
train = torchvision.datasets.MNIST("", train=True, download=True, transform = transforms.Compose([transforms.ToTensor()]))

#test = datasets.MNIST("", train=False, download=True, transform = transforms.Compose([transforms.ToTensor()]))

KeyboardInterrupt: 

In [ ]:
train_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('/files/', train=True, download=True,
                             transform=torchvision.transforms.Compose([
                               torchvision.transforms.ToTensor(),
                               torchvision.transforms.Normalize(
                                 (0.1307,), (0.3081,))
                             ])),
  batch_size=batch_size_train, shuffle=True)

test_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('/files/', train=False, download=True,
                             transform=torchvision.transforms.Compose([
                               torchvision.transforms.ToTensor(),
                               torchvision.transforms.Normalize(
                                 (0.1307,), (0.3081,))
                             ])),
  batch_size=batch_size_test, shuffle=True)